# Generated by Django 3.1.7 on 2021-03-13 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 13, 29, 45, 308997)),
        ),
    ]
