# Generated by Django 3.1.7 on 2021-04-17 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210403_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 23, 42, 21, 445334)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dismissed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='worksSince',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 23, 42, 21, 445334)),
        ),
    ]
