# Generated by Django 3.1.7 on 2021-04-17 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210417_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 23, 53, 18, 323886)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='worksSince',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 23, 53, 18, 323886)),
        )
    ]
