# Generated by Django 3.1.7 on 2021-04-17 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0007_auto_20210417_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 0, 6, 7, 629397)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='worksSince',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 0, 6, 7, 629397)),
        ),
        migrations.RunSQL("ALTER TABLE app_employee ALTER COLUMN \"isActive\" SET DEFAULT TRUE "),
        migrations.RunSQL("ALTER TABLE app_employee ALTER COLUMN \"created\" SET DEFAULT now() "),
        migrations.RunSQL("ALTER TABLE app_employee ALTER COLUMN \"worksSince\" SET DEFAULT now() ")
    ]
