# Generated by Django 3.1.7 on 2021-04-24 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210418_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 23, 15, 51, 83115)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='worksSince',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 23, 15, 51, 83115)),
        ),
        migrations.AlterUniqueTogether(
            name='director',
            unique_together={('department', 'employee')},
        ),
    ]
